---
title: "Machine learning set up"
author: Casey Breen
---

## Fit ML Algos 

```{r}
## set random seed for reproducibility
set.seed(47)  

## library packages 
library(here)
source(here("code", "helpers.R")) ## library all packages for analysis 

## read in death file 
death_file <- read_dta(here("data", "analysis_files", "nfhs5_deaths.DTA")) %>% 
  filter(months_since_death > 3) %>% 
  mutate(registered = as.factor(registered))

## cleam up variable 
death_file <- death_file %>% 
  mutate(facility_distance_quantile = ntile(facility_distance, n = 5)) %>% 
  mutate(road_length_km_quantile = ntile(road_length_km, n = 5))
  
death_file <- death_file %>% 
  filter(!is.na(area_km2))
```

## Create test-train split 

```{r}
## sample splits 
death_file_split <- initial_split(death_file, 0.75)

training_sample <- training(death_file_split)
test_sample  <- testing(death_file_split)
```


```{r}
## define formula 
## note 'features' are defined in helpers.R 
formula <- as.formula(paste("registered ~", paste(vars, collapse = " + ")))
```


```{r}
# set up 10 fold CV
folds_10fold <- vfold_cv(death_file, 10)

# Define the random forest model specification
rf_model <- rand_forest(trees = 500, 
                        min_n = 5,
                        mode = "classification") %>%
  set_engine("ranger", importance = "permutation") ## ranger is a fast random forest implementation 

# Define the recipe for data pre-processing
rf_recipe <- recipe(formula,
                    data = death_file) %>%
  step_dummy(all_nominal_predictors()) %>% # Convert categorical to dummy variables
  step_normalize(all_numeric_predictors()) # Normalize numeric predictors

# Create a workflow
rf_workflow <- workflow() %>%
  add_model(rf_model) %>%
  add_recipe(rf_recipe)

# Fit the model
# Takes 10 min to run 
rf_fit <- rf_workflow %>%
  fit_resamples(resamples = folds_10fold,
                control = control_resamples(save_pred = TRUE))

## get error metrics  
error_metrics_loco_cv <- collect_metrics(rf_fit) 

## get predictions  
predictions <- collect_predictions(rf_fit) 

## combine predictions with original file 
death_file <- death_file %>% 
  mutate(row = row_number())

predictions <- predictions %>% 
  left_join(death_file, by = c(".row" = "row", "registered")) %>% 
    mutate(registered = as.numeric(registered) - 1)

```

## Predicted observed plot 

Plot predictions in 1st percentile, second percentile, etc. 

```{r}
## get predictions 
predicted_observed <- predictions %>% 
  group_by(female) %>% 
  mutate(decile = ntile(.pred_1, 100)) %>% 
  group_by(decile) %>% 
  summarize(reg = mean(registered),
            pred = mean(.pred_1)) %>% 
  ggplot(aes(x = reg, y = pred)) + 
  geom_point() + 
  geom_abline(color = "red", linetype = "dashed") + 
  ylim(0, 1) + 
  xlim(0, 1) + 
  theme_cowplot() + 
  labs(x = "Observed", y = "Predicted")
```


## Make confusion matrix

```{r}
# Create confusion matrix
confusion_matrix <- predictions %>%
  count(registered, .pred_class) %>%
  mutate(prop = paste0(round(n / sum(n) * 100), "%"))

# Plot with corrected code
confusion_matrix_plot <- confusion_matrix %>% 
  mutate(registered = case_when(
    registered == 1 ~ "Yes", 
    TRUE ~ "No")) %>% 
    mutate(.pred_class = case_when(
    .pred_class == 1 ~ "Yes", 
    TRUE ~ "No")) %>% 
  mutate(n_alt = paste0("(", n, ")")) %>% 
ggplot(aes(x = registered, 
           y = .pred_class, fill = n)) +
  geom_tile(color = "white") +
  geom_text(aes(label = prop), vjust = 1.5) +
  geom_text(aes(label = n_alt), vjust = 3.5) +
  scale_fill_gradient(low = "white", high = "steelblue", name = "Count") +
  labs(y = "Predicted", x = "Observed") +
  theme_minimal(base_size = 15) + 
  theme(legend.position = "none")
```

## Distribution of model prediction 

```{r}
distn_fig <- predictions %>% 
  ggplot(aes(x = .pred_1)) + 
  geom_histogram(binwidth = .01, color = "black", fill = "lightblue") +
  theme_cowplot() + 
  labs(x = "Prediction", y = "count")
```


## Create combined plot 

```{r}
## reda in variable importance plot o
var_importance_plot <- read_rds(here("figures", "var_importance.rds"))
interaction_plot <- read_rds(here("figures", "interaction_plot.rds"))

prediction_combined_figure <- plot_grid(predicted_observed, distn_fig, var_importance_plot, interaction_plot, labels = "AUTO")

## predictions 
ggsave(prediction_combined_figure, filename = here("figures", "prediction_combined_figure.png"), height = 10, width= 12, bg = "white") 
```



